# Generated by Django 4.2.7 on 2025-06-30 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BPIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bpin', models.CharField(max_length=50, unique=True)),
                ('nombre_proyecto', models.CharField(max_length=255)),
                ('vigencia', models.IntegerField()),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=50, unique=True)),
                ('objeto_contrato', models.TextField()),
                ('fecha_suscripcion', models.DateField()),
                ('valor_contrato', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bpin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='core.bpin')),
            ],
        ),
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_resolucion', models.CharField(max_length=50, unique=True)),
                ('fecha_resolucion', models.DateField()),
                ('valor_pagado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resoluciones', to='core.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='documentos/%Y/%m/%d/')),
                ('tipo_documento', models.CharField(choices=[('contrato', 'Contrato'), ('resolucion', 'Resolución'), ('adenda', 'Adenda'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('bpin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.bpin')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.contrato')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='bpin',
            index=models.Index(fields=['numero_bpin'], name='core_bpin_numero__6c41c3_idx'),
        ),
        migrations.AddIndex(
            model_name='bpin',
            index=models.Index(fields=['nombre_proyecto'], name='core_bpin_nombre__a19a50_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['bpin', 'contrato'], name='core_docume_bpin_id_52d72a_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['fecha_subida'], name='core_docume_fecha_s_ef3e29_idx'),
        ),
    ]
